name: "Space Corp"

url: "surtrstudios.github.io/spacecorp"

paginate: 10

navigation:
    - text: Home
      url: /
    - text: About Us
      url: /about
    - text: Space Corp
      url: /spacecorp/

authors:
    sean:
      display_name: Sean Kell
      gravatar: 0f3ec550c51eb0689c7feb4fc88bd0ce
      email: sean.michael.kell@gmail.com
      website: http://smkell.github.io
      github: smkell
      about: >
        Sean is a passionate engineer who thinks that it's a good thing to 
        reinvent the wheel from time to time. He enjoys the great outdoors 
        and strategy games of all sorts. His favorite authors include Orson 
        Scott Card, Robert Heinlein, George Orwell, Mark Twain, Charles 
        Dickens, and Geoffrey Chaucer.
    phil:
      display_name: Phil Arth


